### ISSUE TITLE
Error: prybar-python310 not found in $PATH

### ISSUE THREAD

**Issue by senseonegod** [SealedSaucer/Voicecord#13]
Everytime I run it this error appears. I use replit to run it.

Error: prybar-python310 not found in $PATH
repl process died unexpectedly: exit status 1
Error: prybar-python310 not found in $PATH
repl process died unexpectedly: exit status 1
Error: prybar-python310 not found in $PATH
repl process died unexpectedly: exit status 1
Error: prybar-python310 not found in $PATH
repl process died unexpectedly: exit status 1

**Comment by SealedSaucer** [comment]
Hey, please add me on [discord](https://phantom.is-a.dev/verify) so I can help you without any delay.
