### ISSUE TITLE
Website issue

### ISSUE THREAD

**Issue by yvreK** [SealedSaucer/Voicecord#16]
Seems like the website is down? Any fix? 
![Screenshot_2024-01-04-17-15-34-540_com.replit.app-edit.jpg](https://github.com/SealedSaucer/Voicecord/assets/78933419/0101112c-c009-41f6-ae36-03a0ce0bc2a5)

**Comment by skeidGX** [comment]
![image](https://github.com/SealedSaucer/Voicecord/assets/116152785/db6798d8-99d3-4117-a1b9-e286784882cd)

**Comment by yvreK** [comment]
> ![image](https://github.com/SealedSaucer/Voicecord/assets/116152785/db6798d8-99d3-4117-a1b9-e286784882cd)
> 

Seems like I'm the only one who has this? You know why?
