### ISSUE TITLE
main.py fails to run on replit

### ISSUE THREAD

**Issue by UnconsciousPebble** [SealedSaucer/Voicecord#8]
After importing the repository, adding in the token, discord guild and channel IDs and manually joining with the account and trying to run the code in replit, the following error message is displayed and the execution stops
```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    client=commands.Bot(command_prefix=':', self_bot=True, help_command=None)
TypeError: __init__() missing 1 required keyword-only argument: 'intents'
```

**Comment by SealedSaucer** [comment]
It's an issue related with the new discord.py update. Version 2.0 needs everyone to specify the intents whereas in the older versions it just assumed a default intent. I will make an update soon. Thanks.
